### ISSUE TITLE
Data is not saved

### ISSUE THREAD

**Issue by PrintModz** [xperiments/p1touch#14] opened 2023-08-25 10:44 UTC
The problem here is that the data is not saved. After each restart, the printer data has to be re-entered and this is extremely annoying in the long run. Since the problem also exists with some others, it is not a mistake on my part.

Is there already a solution in sight?

**Comment by itsonlymedan** [comment] 2023-08-25 12:01
Known issue check losing config issue

**Comment by grete12** [comment] 2023-08-27 14:03
with me the config is also lost after the restart

**Comment by JudasBrutas** [comment] 2023-08-28 05:17
Same bug here. Settings won't save after shut down. Thank you for all the hard work!

**Comment by xperiments** [comment] 2023-09-09 13:24
Duplicate of #4

**Closed by xperiments** 2023-09-09 13:24 UTC

**Comment by PrintModz** [comment] 2023-09-10 16:35
and new Update?
