### ISSUE TITLE
ESP32 Source? 

### ISSUE THREAD

**Issue by psiberfunk** [xperiments/p1touch#21] opened 2023-08-27 04:21 UTC
Is there any source for the ESP32 BIN file ?

I'm kind of sketched out by flashing an unknown binary without any source to a device I connect to my wifi and printer.  It would increase collaboration and trust if you're able to post some sort of buildable project file for the ESP board?

**Comment by xperiments** [comment] 2023-08-27 17:36
Duplicate of #2

**Closed by xperiments** 2023-08-27 17:36 UTC
